# Generated by Django 5.1.2 on 2024-10-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact_ourproduct_product_ourproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproduct',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
