# Generated by Django 5.1.2 on 2024-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='friends',
            field=models.ManyToManyField(related_name='friend', to='shop.friends'),
        ),
    ]
