# Generated by Django 5.1.2 on 2024-10-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pruduct',
            field=models.ManyToManyField(related_name='pruduct', to='shop.pruduct'),
        ),
    ]
